        FROM php:7.4-fpm
        RUN docker-php-ext-install pdo pdo_mysql

        WORKDIR /var/www
        RUN rm -rf /var/www/html
        # Install composer
        RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

        COPY .  /var/www
        # RUN chown -R www-data:www-data /var/www

        # Aqui estou executando composer install se tiver dependência ele vai instalar
        RUN composer install && \
            cp .env.example .env && \
            php artisan key:generate && \
            php artisan config:cache

        RUN ln -s public html && \
            chmod -R 777 storage
            # Essa parte quando quiser ativar teste unitário do PHPunit
            # vendor/bin/phpunit

        RUN rm -rf /var/lib/apt/lists/*

        # Expose port 9000 and start php-fpm server
        EXPOSE 9000
